name: Format and lint
on:
  push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: get up on this
        uses: actions/checkout@v2

      - name: hit it
        run: ./mk/fmt.sh

      - name: push it
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'andydecleyre@users.noreply.github.com'
          git commit -am 'Format [Automated]' && git push || true
